apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: mock-pump-actuator-mcp
  namespace: smart-farm-demo
spec:
  transportType: http
  deployment:
    image: jainputhore/pump-actuator-mcp:latest
    env:
      REDIS_URL: redis://redis-sim-service.smart-farm-demo.svc.cluster.local:6379
  httpTransport:
    path: /sse
    targetPort: 3001