apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-state-store
  namespace: smart-farm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sim-state
  template:
    metadata:
      labels:
        app: redis-sim-state
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sim-service
  namespace: smart-farm-demo
spec:
  selector:
    app: redis-sim-state
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
