apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-sensor-simulator
  namespace: smart-farm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-sensor
  template:
    metadata:
      labels:
        app: soil-sensor
    spec:
      containers:
      - name: simulator
        image: mock-soil-mcp:latest
        imagePullPolicy: Never # Prevent trying to pull from remote registry
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mock-soil-sensor-mcp-service
  namespace: smart-farm-demo
spec:
  selector:
    app: soil-sensor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
